### ISSUE TITLE
How can I use RSpec::Mocks with Spinach ?

### ISSUE THREAD

**Issue by crisefd** [codegram/spinach#193]
I've been trying to setup my `env.rb` to include the mocks module, no luck so far. I faced a similar issue when including the matchers, for that I add `include 'rspec/expectations'` so I tried to add `rspec/mocks`, but I still get this error when trying to stub/mock a class using `instance_double()`:
`  undefined method 'instance_double' for #<Spinach::Features::MyStepClass `

**Comment by pedantic-git** [comment]
I just had the same issue so I fixed it up the same way Cucumber does. Check out PR #195!

**Comment by oriolgual** [comment]
Thanks @pedantic-git & @crisefd! I just merged #195
