### ISSUE TITLE
Use two reporters at once

### ISSUE THREAD

**Issue by jabbett** [codegram/spinach#199]
Our build server uses the [spinach-rerun-reporter](https://github.com/javierav/spinach-rerun-reporter) to collect a list of failing tests in a file and then rerun them automatically.

However, when specifying that reporter -- `-r rerun` -- Spinach also seems to use the console reporter.

Ideally, we'd prefer the visible output of the progress reporter so our build logs aren't so verbose.

Could Spinach somehow accept multiple reporters -- e.g. `-r progress,rerun` -- like other test runners (Cucumber, Karma) do?

**Comment by oriolgual** [comment]
I think it could be done @jabbett, it might need some work but it's doable. Do you think you could come up with a PR with it?

/cc @ywen @javierav

**Comment by jabbett** [comment]
I'll give it a try.
