### ISSUE TITLE
Cut a new gem version?

### ISSUE THREAD

**Issue by jstuckey** [codegram/spinach#203]
Hey, folks. Would it be possible to release a new version of this gem? There are a handful of PRs merged to master since the 0.10.0 release.

**Comment by Papipo** [comment]
Is this somewhat unmaintained? That would be a shame, I am tryin to introduce it in the company I work for instead of cucumber :(

**Comment by oriolgual** [comment]
Sorry about the delay, I've pushed a new gem version (0.10.1) to RubyGems!

**Comment by jstuckey** [comment]
Thanks, @oriolgual!

**Comment by jstuckey** [comment]
@Papipo we have a few teams using Spinach at work, and it's worked out well so far.

**Comment by ywen** [comment]
@Papipo If there is demands and requests I am more than happy to work on or review the PR and so on.

**Comment by Papipo** [comment]
What about [official] support for ruby 2.4/2.5 😁
