### ISSUE TITLE
Release random order

### ISSUE THREAD

**Issue by Bertg** [codegram/spinach#211]
I see that there is a "randomize scenario" feature merged. 
Any change this can be officially released?

Thx!

**Comment by simi** [comment]
Would be amazing!

**Comment by oriolgual** [comment]
Released under 0.12.0, sorry for the extremely long delay!

**Comment by simi** [comment]
Better late than never.

**Comment by Bertg** [comment]
> Released under 0.12.0, sorry for the extremely long delay!

Today I saw [a PR on an other project](https://github.com/ci-reporter/ci_reporter/pull/160) that opened in 2016 and last activity in 2018 get merged as well. 

It's amazing to see maintainers get any work done. If it takes 1 hour, a year or several, the work is appreciated.
