### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by justthisguy** [codegram/spinach#213]
While starting a new product, I came across Spinach and am quite interested in using it instead of Cucumber but then I saw that <https://www.ruby-toolbox.com/projects/spinach> says people stopped downloading it in 2017 and  <https://github.com/codegram/spinach/commits/master> says that Jun 4, 2018 was the last commit. 

What is the status of this project? Who is actively working on it?

Thank you for all the efforts you have put it so far!

**Comment by ywen** [comment]
I am a maintainer but have no merge permission. I would really love to continue supporting this great tool. If no maintainer responds to this message in 3 days. I will fork the project and start maintaining. In the meantime you should be able to use it.

**Comment by oriolgual** [comment]
Sorry @ywen I thought you already had permissions, I've set you as maintainer!

**Comment by ywen** [comment]
Thank you!

**Comment by ywen** [comment]
@oriolgual I also realize I don't have permission to release a gem. Could you please release a new version? Thanks!

**Comment by mrcasals** [comment]
@ywen in order to add you to Rubygems we need your email there! I have my email public in my GitHub profile, can you send me an email there specifying what email you use in Rubygems? To verify it's you, please send the email from the email address you use to create git commits! 😄

**Comment by ywen** [comment]
As I can release gems now, closing this issue
