### ISSUE TITLE
Enable Support For Ruby v3.2

### ISSUE THREAD

**Issue by lym** [codegram/spinach#241]
### Is your feature request related to a problem?

I get a `NoMethodError` error when I try running _spinach_ against the latest Ruby version (v3.2). This is because at [this line](https://github.com/codegram/spinach/blob/master/lib/spinach/cli.rb#L59), spinach references the `File.exists?` method. This method was obsoleted by Ruby v3.2. Please see [here](https://bugs.ruby-lang.org/issues/17391).

### Describe the solution you'd like

Updating the line referenced above to `File.exist?` solves the problem for me and I am able to use `spinach` with the latest Ruby version.

**Comment by oriolgual** [comment]
Fixed at #243
