### ISSUE TITLE
Add RSpec::Machers support

### ISSUE THREAD

**Issue by pwoloszun** [codegram/spinach#87]
Currently in order to use RSpec machers in steps definitions I've got to:
1) require 'rspec' in env.rb
2) add: include RSpec::Machers, to each step class(class that inherits from Spinach::FeatureSteps)

**Comment by montskak** [comment]
@paullaz I got around having to use `Spinach::FeatureSteps.send(:include, RSpec::Matchers)` by requiring `rspec/expectations` in `env.rb`. 
I think it has something to do with `rspec-rails`, but I haven't looked into it much further.
